/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const SkillsLazyImport = createFileRoute('/skills')()
const LicenseLazyImport = createFileRoute('/license')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const SkillsLazyRoute = SkillsLazyImport.update({
  path: '/skills',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/skills.lazy').then((d) => d.Route))

const LicenseLazyRoute = LicenseLazyImport.update({
  path: '/license',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/license.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/license': {
      id: '/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof LicenseLazyImport
      parentRoute: typeof rootRoute
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  LicenseLazyRoute,
  SkillsLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "children": [
        "/",
        "/license",
        "/skills"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/license": {
      "filePath": "license.lazy.tsx"
    },
    "/skills": {
      "filePath": "skills.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
